server:
  port: ${SERVER_PORT:8110}
spring:
  boot:
    admin:
      client:
        url: http://localhost:8000
        enabled: false
  sql:
    init:
      continue-on-error: true
  datasource:
    continue-on-error: true
    url: jdbc:mysql://127.0.0.1:3306/data_collection?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowLoadLocalInfile=false&allowLoadLocalInfileInPath=/&allowUrlInLocalInfile=false&allowLoadLocalInfileInPath=&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: false

  application:
    name: @artifactId@

  kafka:
    bootstrap-servers: 8.135.25.69:9092
    consumer:
      properties:
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin";'
        security.protocol: SASL_PLAINTEXT
    listener:
      concurrency: 3
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    name: logs/${spring.application.name}/debug.log
  level:
    root: info
    org.springframework.boot: info

opencloud:
  swagger2:
    enabled: true
    description: 代码快速开发库
    title: 代码快速开发库

mybatis-plus:
  typeAliasesPackage: cn.oj.codebase.generator.dto,cn.cary.codebase.**.entity
  mapper-locations: classpath*:mapper/**/*.xml

mybatis:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler

elasticsearch:
  hostlist: ${eshostlist:127.0.0.1:9200}







